version: '3.8'

services:
  webserver:
    image: moviecenter:latest
    ports:
      - "80:${WEBSERVER_PORT}"
  mongodb:
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    volumes:
      - ~/apps/moviecenter/mongo:/data/db
